export const SET_INTEREST_RATE = 'SET_INTEREST_RATE';
export const SET_MORTGAGE_LENGTH = 'SET_MORTGAGE_LENGTH';
export const CALCULATE_MONTHLY_PAYMENT = 'CALCULATE_MONTHLY_PAYMENT';
export const SET_DOWN_PAYMENT = 'SET_DOWN_PAYMENT';
export const SET_TOTAL_MORTGAGE = 'SET_TOTAL_MORTGAGE';
