export const SET_MONTHLY_BUDGET = 'SET_MONTHLY_BUDGET';
export const SET_CURRENT_AMOUNT_IN_RETIREMENT =
  'SET_CURRENT_AMOUNT_IN_RETIREMENT';
export const CALCULATE_AMOUNT_NEEDED_IN_RETIREMENT =
  'CALCULATE_AMOUNT_NEEDED_IN_RETIREMENT';
export const CALCULATE_ADDITIONAL_SAVINGS_NEEDED_TO_RETIRE =
  'CALCULATE_ADDITIONAL_SAVINGS_NEEDED_TO_RETIRE';
export const CALCULATE_YEARS_UNTIL_RETIREMENT =
  'CALCULATE_YEARS_UNTIL_RETIREMENT';
